name: Hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: "actions/checkout@v3"
      - name: Hassfest
        uses: "home-assistant/actions/hassfest@master"
